### ISSUE TITLE
docker issues with .env file variables

### ISSUE THREAD

**Issue by AlexHTW** [n3d1117/chatgpt-telegram-bot#170]
## Problem description
Using the docker-run command doesn't parse enquoted values in the .env file correctly.
If essential values such as the tokens are enquoted, the bot will fail to start. If other values are enquoted it will lead to wrong behaviour or error messages during runtime.

### Related Issues
#140 #168

## Cause
`docker run` [doesn't parse .env files by a shell](https://stackoverflow.com/a/70104500).
`docker compose up` or running it locally with `python bot/main.py` does use shell parsing.

## Current workaround
Remove all quotation marks in the .env file. (Correct behavior not tested for all of the variables, but so far so good.)

## Additional issue with .env file for future development
Changes to the .env file within the program can not be persisted when using docker, blocking #139 and #108.

## Goal
(1) A unified environment file that works with all three options of running the bot and (2) is mutable from within the docker container.

## Solution ideas
- (1) don't use any quotation marks in .env for any of the three options 
    - only did little testing but seems to work with current implementation already
    - verify all variables for all three run options and update `README` and `.env.example` or `main.py` if needed
- (2) only pass .env file when you want to overwrite the current settings or on first setup
    - values are copied to an .env file equivalent within the container that is mutable
    - values can be updated and persisted on the internal .env file
    - use `entrypoint.sh` for docker run and `docker-compose.yml` for docker compose up to define this behaviour
    - running locally with python bot/main.py can keep using just the one .env file
    - might lead to misunderstandings and accidental overwriting of settings

Looking forward to input from people who have some docker experience (I don't 😛).

**Comment by n3d1117** [comment]
Thanks for the writeup @AlexHTW! I don't have time to look into this either (nor do I have any significant docker experience 😃), but I hope someone can shed some light on it!

**Comment by NoobGinger** [comment]
As I encountered an issue with the parsing of enquoted values in the .env file while using the docker-run command, I realized that essential values such as tokens, when enquoted, caused the bot to fail during startup. Furthermore, enquoted values led to incorrect behavior or error messages during runtime.

To resolve this issue, I made sure not to use quotes in my .env file when defining values. Instead of writing:

makefile

TELEGRAM_BOT_TOKEN="123456:ABC-DEF"

I wrote:

ruby

TELEGRAM_BOT_TOKEN=123456:ABC-DEF

By removing the quotes, I avoided any parsing problems. As long as I didn't have any spaces or special characters in my values that required quotes, my bot worked fine without using them.

**Comment by NoobGinger** [comment]
To handle spaces in ASSISTANT_PROMPT, replace spaces with underscores in the .env file and use this line in main.py:

**Comment by wenzelt** [comment]
I am experiencing the same Issue with the USER_IDs

**Comment by n3d1117** [comment]
Removed quotes from all vars in `.env.example`(except assistant prompt) https://github.com/n3d1117/chatgpt-telegram-bot/commit/c6932c8a12664fd69225eb95dbff7068772f2d0a
