### ISSUE TITLE
docker-compose ERROR: No matching distribution found for openaiauth

### ISSUE THREAD

**Issue by ch3ckmat3** [n3d1117/chatgpt-telegram-bot#27]
I am getting this error when trying docker-compose on Docker Desktop (Win10)
From docker logs:
```
#0 9.421 [pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement openaiauth==0.0.6 (from versions: none)
#0 9.421 [pipenv.exceptions.InstallError]: ERROR: No matching distribution found for openaiauth==0.0.6
```

Wehn I try to install using pip command, same error:
```
>  pip install openaiauth
ERROR: Could not find a version that satisfies the requirement openaiauth (from versions: none)
ERROR: No matching distribution found for openaiauth
```

What am I missing?

**Comment by n3d1117** [comment]
Hi @ch3ckmat3 this tool is no longer working as of December 12th. The error you're seeing is probably due to changes in the underlying [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT) repository.

I don't have a fix, however I'll update this repo as soon as official ChatGPT APIs are relased.

**Comment by ch3ckmat3** [comment]
I understand. Thank you for your reply. Looking forward to getting updates. ✌
