### ISSUE TITLE
/reset <something> doesn't seem to have any effect

### ISSUE THREAD

**Issue by alparo** [n3d1117/chatgpt-telegram-bot#319]
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/390857/82110f7a-e698-463c-863b-90d6243ba64e)
See the screenshot. According to the manual the message after /reset should be taken as initial prompt for the ChatGPT, but it is not the case.

**Comment by n3d1117** [comment]
Hey there, works here 
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/11541888/1486f4c4-b289-4138-b57e-7cebe4d5d1fa)

You could try some variations with your prompt. Like "you now act like thor" instead of "your name is thor". 

Keep in mind  ([source](https://platform.openai.com/docs/guides/chat/introduction)):

> [gpt-3.5-turbo-0301](https://platform.openai.com/docs/models) does not always pay strong attention to system messages. Future models will be trained to pay stronger attention to system messages.

System messages should improve with gpt-4!
