### ISSUE TITLE
This model's maximum context length is 4096 tokens.

### ISSUE THREAD

**Issue by x011** [n3d1117/chatgpt-telegram-bot#45]
`This model's maximum context length is 4096 tokens.`

Is there a way to bypass this?

**Comment by n3d1117** [comment]
Hi @x011, no I don't think so. I guess you need to split the output into multiple responses

**Comment by AlexHTW** [comment]
Hi @x011, the token usage per request is [limited by OpenAI](https://platform.openai.com/docs/models/overview). That means 4096 tokens for prompt+request.
Because the API does not implement a state, every prompt has to include the whole conversation history which leads to a rapidly growing request size.
The automatic conversation summary implemented in release 0.1.4 of this project helps to prevent that and enables longer conversations by summarizing the history after x (=10) messages to around 175 tokens. Setting the "MAX_HISTORY_SIZE" value in your .env lower will shorten your conversation history more frequently but may imply worse memory for your bot.
Additionally you can limit the token usage the bot can use for its answer with "MAX_TOKENS", but I don't think that was the issue for you.

@n3d1117 
To implement a "robust" solution the conversation summary could be triggered when the token amount of the prompt + MAX_TOKENS > 4096.

**Comment by n3d1117** [comment]
Good idea @AlexHTW. I guess that means adding the [tiktoken](https://github.com/openai/tiktoken) library as dependency to calculate number of tokens for a prompt in advance. Added to the README in case some wants to pick it up!

**Comment by mithew** [comment]
except openai.error.InvalidRequestError as e:
            logging.exception(e)
            oldest = self.conversations[chat_id][0]    
            newest = self.conversations[chat_id][-2:]
            self.conversations[chat_id] = [oldest] + newest
            return self.get_chat_response(chat_id, query)

**Comment by n3d1117** [comment]
Added token counting with #72 .@x011 can you check it out and see if it fixes your issue?

**Comment by x011** [comment]
@n3d1117 Seems ok for me now, tks.
